### ISSUE TITLE
Might this be a windows problem?

### ISSUE THREAD

**Issue by ptraceur** [tsframework/ts-framework#38]
Hi,
I've tried to use this on a windows machine(didn't tested witg other OS's). Node version 5, and last stable TS version.

![shell](http://image.prntscr.com/image/a6668fe0d2504894a7e1cadef6291bd7.png)

Any ideas?

**Comment by atrakeur** [comment]
To me it look like a tsc error (version or whatever)

However I'm not sure because the framework isn't really stable and usable at the moment.

There is a stable release coming in in the next weeks.

**Comment by ptraceur** [comment]
Oh ok, glad to know that. 
Thanks for your help 😄 

Will wait for the stable release.
